'use client';
import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import api from '@/lib/api';
import { apiError } from '@/lib/format';

export default function CatalogManagement({ canManage = false }) {
  const [categories, setCategories] = useState([]); const [universities, setUniversities] = useState([]); const [name, setName] = useState(''); const [universityName, setUniversityName] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { try { const [c, u] = await Promise.all([api.get('/platform/catalog/categories'), api.get('/platform/catalog/universities')]); setCategories(c.categories || []); setUniversities(u.universities || []); } catch (error) { toast.error(apiError(error)); } };
  useEffect(() => { load(); }, []);
  const addCategory = async (event) => { event.preventDefault(); if (!name.trim()) return; setBusy(true); try { await api.post('/platform/catalog/categories', { name: name.trim(), orderIndex: categories.length + 1 }); setName(''); await load(); toast.success('تمت إضافة التصنيف'); } catch (error) { toast.error(apiError(error)); } finally { setBusy(false); } };
  const reorder = async (index, direction) => { const next = index + direction; if (next < 0 || next >= categories.length) return; const current = categories[index]; const target = categories[next]; try { await Promise.all([api.put(`/platform/catalog/categories/${current.id}`, { name: current.name, description: current.description || null, iconUrl: current.icon_url || null, orderIndex: target.order_index }), api.put(`/platform/catalog/categories/${target.id}`, { name: target.name, description: target.description || null, iconUrl: target.icon_url || null, orderIndex: current.order_index })]); await load(); } catch (error) { toast.error(apiError(error)); } };
  const toggle = async (id, active, type) => { try { await api.patch(`/platform/catalog/${type}/${id}/status`, { isActive: !active }); await load(); } catch (error) { toast.error(apiError(error)); } };
  const addUniversity = async (event) => { event.preventDefault(); if (!universityName.trim()) return; setBusy(true); try { await api.post('/platform/catalog/universities', { name: universityName.trim(), orderIndex: universities.length + 1, isActive: true }); setUniversityName(''); await load(); toast.success('تمت إضافة الجامعة'); } catch (error) { toast.error(apiError(error)); } finally { setBusy(false); } };
  return <div className="space-y-6"><div><h2 className="text-xl font-black">إدارة التصنيفات والجامعات</h2><p className="mt-2 text-sm leading-7 text-secondary-600">يمكنك الإضافة والتعطيل دون حذف البيانات المرتبطة بالمنتجات والطلبات القديمة.</p></div><section className="rounded-2xl bg-white p-5 shadow-card"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-black">التصنيفات</h3>{canManage && <form onSubmit={addCategory} className="flex gap-2"><input className="input-base" placeholder="اسم تصنيف جديد" value={name} onChange={(e) => setName(e.target.value)} /><button disabled={busy} className="btn-primary">إضافة</button></form>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2">{categories.map((category) => <div key={category.id} className="rounded-xl border border-secondary-100 p-4"><div className="flex items-center justify-between gap-3"><div><b>{category.name}</b><p className="mt-1 text-xs text-secondary-500">{category.subCategories?.length || 0} تصنيف فرعي · ترتيب {category.order_index}</p></div>{canManage && <div className="flex gap-1"><button title="تحريك للأعلى" onClick={() => reorder(categories.indexOf(category), -1)} className="btn-secondary text-xs">↑</button><button title="تحريك للأسفل" onClick={() => reorder(categories.indexOf(category), 1)} className="btn-secondary text-xs">↓</button><button onClick={() => toggle(category.id, category.is_active, 'categories')} className="btn-secondary text-xs">{category.is_active ? 'تعطيل' : 'تفعيل'}</button></div>}</div>{category.subCategories?.length > 0 && <p className="mt-3 text-xs leading-6 text-secondary-600">{category.subCategories.map((sub) => sub.name).join('، ')}</p>}</div>)}</div></section><section className="rounded-2xl bg-white p-5 shadow-card"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-black">الجامعات</h3>{canManage && <form onSubmit={addUniversity} className="flex gap-2"><input className="input-base" placeholder="اسم جامعة جديدة" value={universityName} onChange={(e) => setUniversityName(e.target.value)} /><button disabled={busy} className="btn-primary">إضافة</button></form>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{universities.map((university) => <div key={university.id} className="flex items-center justify-between gap-3 rounded-xl border border-secondary-100 p-4"><div><b>{university.name}</b><p className="mt-1 text-xs text-secondary-500">{university.province?.name || 'كل المحافظات'}</p></div>{canManage && <button onClick={() => toggle(university.id, university.is_active, 'universities')} className="btn-secondary text-xs">{university.is_active ? 'تعطيل' : 'تفعيل'}</button>}</div>)}</div></section></div>;
}
