'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import api from '@/lib/api';
import { useAuth } from '@/context/AuthContext';
import { apiError, formatDate, formatMoney, orderStatuses } from '@/lib/format';
import ProductForm from '@/components/ProductForm';
import AssignDriverDialog from './AssignDriverDialog';
import DashboardShell from './DashboardShell';
import DataTable from './DataTable';
import DetailPanel from './DetailPanel';
import RejectDialog from './RejectDialog';
import RolePermissionMatrix from './RolePermissionMatrix';
import StatsCard from './StatsCard';

const statusBadge = (status) => <span className="rounded-full bg-secondary-100 px-2.5 py-1 text-xs font-bold">{orderStatuses[status] || status}</span>;
const request = async (fn) => { try { return await fn(); } catch (error) { toast.error(apiError(error)); return null; } };
const query = (filters) => { const params = new URLSearchParams(); Object.entries(filters || {}).forEach(([key, value]) => value !== '' && value !== undefined && value !== null && params.set(key, value)); return params.toString() ? `?${params}` : ''; };

function Filters({ companies, value, onChange, fields = ['search', 'companyId', 'minTotal', 'maxTotal'] }) {
  const set = (key, next) => onChange({ ...value, [key]: next });
  return <div className="grid gap-3 rounded-2xl bg-white p-4 shadow-card sm:grid-cols-2 lg:grid-cols-5"><input className="input-base" placeholder="بحث بالاسم أو الرقم…" value={value.search || ''} onChange={(e) => set('search', e.target.value)} />{fields.includes('companyId') && <select className="input-base" value={value.companyId || ''} onChange={(e) => set('companyId', e.target.value)}><option value="">كل الشركات</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.company_name}</option>)}</select>}{fields.includes('status') && <select className="input-base" value={value.status || ''} onChange={(e) => set('status', e.target.value)}><option value="">كل الحالات</option><option value="pending">معلّق</option><option value="approved">معتمد</option><option value="rejected">مرفوض</option><option value="completed">مكتمل</option></select>}{fields.includes('minTotal') && <input className="input-base" type="number" placeholder="من السعر" value={value.minTotal || ''} onChange={(e) => set('minTotal', e.target.value)} />}{fields.includes('maxTotal') && <input className="input-base" type="number" placeholder="إلى السعر" value={value.maxTotal || ''} onChange={(e) => set('maxTotal', e.target.value)} />}<input className="input-base" type="date" value={value.from || ''} onChange={(e) => set('from', e.target.value)} /><input className="input-base" type="date" value={value.to || ''} onChange={(e) => set('to', e.target.value)} /></div>;
}

export default function OperationalDashboard({ title, eyebrow }) {
  const { can, user } = useAuth();
  const [active, setActive] = useState('overview');
  const [data, setData] = useState({});
  const [loading, setLoading] = useState(true);
  const [assigning, setAssigning] = useState(null);
  const [rejecting, setRejecting] = useState(null);
  const [showProductForm, setShowProductForm] = useState(false);
  const [detail, setDetail] = useState({ open: false, title: '', data: null, loading: false });
  const [filters, setFilters] = useState({});
  const [companies, setCompanies] = useState([]);

  const items = useMemo(() => [{ id: 'overview', label: 'الرئيسية', permission: 'dashboard.view' }, { id: 'orders', label: 'الطلبات', permission: 'orders.view' }, { id: 'companies', label: 'الشركات', permission: 'companies.view' }, { id: 'products', label: 'المنتجات', permission: 'products.view' }, { id: 'roles', label: 'الأدوار والصلاحيات', permission: 'roles.view' }, { id: 'drivers', label: 'السائقون', permission: 'drivers.view' }, { id: 'invoices', label: 'الفواتير والتحصيل', anyOf: ['invoices.view', 'finance.view'] }, { id: 'audit', label: 'سجل النشاط', permission: 'audit.view' }], []);
  const activeFilters = filters[active] || {};
  const setActiveFilters = (next) => setFilters((current) => ({ ...current, [active]: next }));

  const load = useCallback(async () => {
    setLoading(true);
    const sources = [['dashboard', 'dashboard.view', '/platform/dashboard'], ['orders', 'orders.view', `/platform/orders${query(filters.orders)}`], ['companies', 'companies.view', '/platform/companies'], ['products', 'products.view', `/platform/products${query(filters.products)}`], ['roles', 'roles.view', '/platform/roles'], ['drivers', 'drivers.view', `/platform/drivers${query(filters.drivers)}`], ['invoices', 'invoices.view', `/platform/invoices${query(filters.invoices)}`], ['audit', 'audit.view', '/platform/audit-log']].filter(([, permission]) => can(permission));
    const values = await Promise.all(sources.map(async ([key, , url]) => [key, await request(() => api.get(url))]));
    const next = Object.fromEntries(values); setData(next); setCompanies(next.companies?.companies || []); setLoading(false);
  }, [can, filters]);
  useEffect(() => { load(); }, [load]);

  const openDetail = async (url, titleText) => { setDetail({ open: true, title: titleText, data: null, loading: true }); const response = await request(() => api.get(url)); if (response) setDetail({ open: true, title: titleText, data: response, loading: false }); else setDetail((current) => ({ ...current, loading: false })); };
  const setOrderStatus = async (order, status, reason) => { const response = await request(() => api.patch(`/platform/orders/${order.id}/status`, { status, ...(reason ? { reason } : {}) })); if (response) { toast.success(response.message || 'تم تحديث الطلب'); setRejecting(null); load(); } };
  const assignDriver = async ({ driverId, note }) => { const response = await request(() => api.post(`/platform/orders/${assigning.id}/assign-driver`, { driverId, note: note || undefined })); if (response) { toast.success('تم تعيين السائق'); setAssigning(null); load(); } };
  const toggleCompany = async (company) => { const response = await request(() => api.patch(`/platform/companies/${company.id}/status`, { isActive: !company.is_active })); if (response) { toast.success(response.message); load(); } };
  const toggleDriver = async (driver) => { const response = await request(() => api.patch(`/platform/drivers/${driver.id}/status`, { isActive: !driver.is_active, isAvailable: driver.is_available })); if (response) { toast.success('تم تحديث حالة السائق'); load(); } };

  const stats = data.dashboard?.stats || {};
  const content = active === 'overview' ? <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatsCard label="إجمالي الطلبات" value={stats.orders || 0} onClick={() => setActive('orders')} /><StatsCard label="طلبات جديدة" value={stats.newOrders || 0} onClick={() => setActive('orders')} /><StatsCard label="قيد التوصيل" value={stats.inDelivery || 0} onClick={() => setActive('orders')} /><StatsCard label="المبيعات المكتملة" value={formatMoney(stats.totalSales, 'SYP')} onClick={() => setActive('invoices')} /><StatsCard label="غير المحصل" value={formatMoney(stats.uncollected, 'SYP')} onClick={() => setActive('invoices')} /><StatsCard label="الشركات" value={stats.companies || 0} onClick={() => setActive('companies')} /><StatsCard label="منتجات بانتظار الاعتماد" value={stats.pendingProducts || 0} onClick={() => setActive('products')} /><StatsCard label="إجمالي التحصيلات" value={formatMoney(stats.collections, 'SYP')} onClick={() => setActive('invoices')} /></div><div className="rounded-2xl bg-white p-6 shadow-card"><h2 className="text-xl font-black">مركز إدارة المنصة</h2><p className="mt-3 leading-7 text-secondary-600">استخدم أزرار التفاصيل لفتح الملف الكامل، واستعمل الفلاتر للوصول السريع إلى الطلبات والفواتير والمنتجات والسائقين.</p></div></div>
    : active === 'orders' ? <div className="space-y-4"><h2 className="text-xl font-black">إدارة الطلبات والتفاصيل الكاملة</h2><Filters companies={companies} value={activeFilters} onChange={setActiveFilters} fields={['search', 'companyId', 'status', 'minTotal', 'maxTotal']} /><DataTable rows={data.orders?.orders || []} empty="لا توجد طلبات ضمن الفلاتر الحالية." columns={[{ key: 'order_number', label: 'الطلب' }, { key: 'merchant', label: 'الشركة', render: (order) => order.merchant?.company_name || '—' }, { key: 'status', label: 'الحالة', render: (order) => statusBadge(order.status) }, { key: 'total', label: 'الإجمالي', render: (order) => formatMoney(order.total, order.currency) }, { key: 'actions', label: 'إجراءات', render: (order) => <div className="flex flex-wrap gap-2"><button className="btn-secondary text-xs" onClick={() => openDetail(`/platform/orders/${order.id}`, `تفاصيل الطلب ${order.order_number}`)}>التفاصيل الكاملة</button>{can('orders.review') && order.status === 'new' && <button onClick={() => setOrderStatus(order, 'pending_review')} className="btn-secondary text-xs">بدء المراجعة</button>}{can('orders.approve') && order.status === 'pending_review' && <button onClick={() => setOrderStatus(order, 'approved')} className="btn-primary text-xs">موافقة</button>}{can('orders.reject') && order.status === 'pending_review' && <button onClick={() => setRejecting({ order, status: 'rejected', title: 'سبب رفض الطلب' })} className="btn-secondary text-xs text-red-700">رفض</button>}{can('orders.change_status') && order.status === 'approved' && <button onClick={() => setOrderStatus(order, 'preparing')} className="btn-primary text-xs">بدء التجهيز</button>}{can('orders.change_status') && order.status === 'preparing' && <button onClick={() => setOrderStatus(order, 'ready_for_delivery')} className="btn-primary text-xs">جاهز للتوصيل</button>}{can('orders.assign_driver') && order.status === 'ready_for_delivery' && <button onClick={() => setAssigning(order)} className="btn-primary text-xs">تعيين سائق</button>}{can('orders.final_review') && order.status === 'final_review' && <button onClick={() => setOrderStatus(order, 'completed')} className="btn-primary text-xs">إكمال</button>}</div> }]} /></div>
    : active === 'companies' ? <div className="space-y-4"><h2 className="text-xl font-black">الشركات ونشاطها</h2><DataTable rows={data.companies?.companies || []} empty="لا توجد شركات ضمن نطاقك." columns={[{ key: 'company_name', label: 'الشركة' }, { key: 'province', label: 'المحافظة' }, { key: 'approval_status', label: 'الاعتماد' }, { key: 'is_active', label: 'الحالة', render: (company) => company.is_active ? 'فعالة' : 'معطلة' }, { key: 'actions', label: 'إجراءات', render: (company) => <div className="flex flex-wrap gap-2"><button className="btn-secondary text-xs" onClick={() => openDetail(`/platform/companies/${company.id}`, `ملف الشركة: ${company.company_name}`)}>التفاصيل والنشاط</button>{can('companies.disable') && <button className="btn-secondary text-xs" onClick={() => toggleCompany(company)}>{company.is_active ? 'تعطيل' : 'تفعيل'}</button>}</div> }]} /></div>
    : active === 'products' ? <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">إدارة المنتجات والتفاصيل</h2>{can('products.create') && user?.companyIds?.length === 1 && <button onClick={() => setShowProductForm((current) => !current)} className="btn-primary">{showProductForm ? 'إخفاء النموذج' : 'إضافة منتج'}</button>}</div><Filters companies={companies} value={activeFilters} onChange={setActiveFilters} fields={['search', 'companyId', 'status', 'minTotal', 'maxTotal']} />{showProductForm && <section className="rounded-2xl bg-white p-6 shadow-card"><ProductForm endpoint="/products" onSuccess={() => { setShowProductForm(false); load(); }} /></section>}<DataTable rows={data.products?.products || []} empty="لا توجد منتجات ضمن الفلاتر الحالية." columns={[{ key: 'name', label: 'المنتج' }, { key: 'merchant', label: 'الشركة', render: (product) => product.merchant?.company_name || '—' }, { key: 'stock_quantity', label: 'المخزون' }, { key: 'status', label: 'الحالة', render: (product) => statusBadge(product.status) }, { key: 'actions', label: 'إجراءات', render: (product) => <div className="flex flex-wrap gap-2"><button className="btn-secondary text-xs" onClick={() => openDetail(`/platform/products/${product.id}`, `ملف المنتج: ${product.name}`)}>التفاصيل الكاملة</button>{can('products.approve') && product.status === 'pending' && <button onClick={async () => { const response = await request(() => api.patch(`/platform/products/${product.id}/status`, { status: 'approved' })); if (response) { toast.success('تم اعتماد المنتج'); load(); } }} className="btn-primary text-xs">اعتماد</button>}{can('products.reject') && product.status === 'pending' && <button onClick={() => setRejecting({ product, status: 'rejected', title: 'سبب رفض المنتج' })} className="btn-secondary text-xs text-red-700">رفض</button>}{can('products.hide') && product.is_active && <button onClick={async () => { const response = await request(() => api.patch(`/platform/products/${product.id}/status`, { status: 'inactive' })); if (response) { toast.success('تم إخفاء المنتج'); load(); } }} className="btn-secondary text-xs">إخفاء</button>}</div> }]} /></div>
    : active === 'roles' ? <RolePermissionMatrix roles={data.roles?.roles || []} permissions={data.roles?.permissions || []} canEdit={can('roles.assign')} onSaved={load} />
    : active === 'drivers' ? <div className="space-y-4"><h2 className="text-xl font-black">السائقون والتحكم الكامل</h2><Filters companies={companies} value={activeFilters} onChange={setActiveFilters} fields={['search', 'companyId']} /><DataTable rows={data.drivers?.drivers || []} empty="لا يوجد سائقون ضمن الفلاتر الحالية." columns={[{ key: 'user', label: 'السائق', render: (driver) => driver.user?.full_name || '—' }, { key: 'driver_type', label: 'النوع' }, { key: 'plate_number', label: 'اللوحة' }, { key: 'is_available', label: 'التوفر', render: (driver) => driver.is_available ? 'متاح' : 'غير متاح' }, { key: 'actions', label: 'إجراءات', render: (driver) => <div className="flex flex-wrap gap-2"><button className="btn-secondary text-xs" onClick={() => openDetail(`/platform/drivers/${driver.id}`, `ملف السائق: ${driver.user?.full_name || 'بدون اسم'}`)}>التفاصيل والمهام</button>{can('drivers.disable') && <button className="btn-secondary text-xs" onClick={() => toggleDriver(driver)}>{driver.is_active ? 'تعطيل' : 'تفعيل'}</button>}</div> }]} /></div>
    : active === 'invoices' ? <div className="space-y-4"><h2 className="text-xl font-black">الفواتير والتحصيل على مستوى المنصة</h2><Filters companies={companies} value={activeFilters} onChange={setActiveFilters} fields={['search', 'companyId', 'minTotal', 'maxTotal']} /><DataTable rows={data.invoices?.invoices || []} empty="لا توجد فواتير ضمن الفلاتر الحالية." columns={[{ key: 'invoice_number', label: 'رقم الفاتورة' }, { key: 'company', label: 'الشركة', render: (invoice) => invoice.company?.company_name || 'المنصة' }, { key: 'customer', label: 'العميل', render: (invoice) => invoice.customer?.full_name || '—' }, { key: 'total', label: 'الإجمالي', render: (invoice) => formatMoney(invoice.total, invoice.currency) }, { key: 'issued_at', label: 'التاريخ', render: (invoice) => formatDate(invoice.issued_at, true) }, { key: 'actions', label: 'إجراءات', render: (invoice) => <button className="btn-secondary text-xs" onClick={() => openDetail(`/platform/invoices/${invoice.id}`, `تفاصيل الفاتورة: ${invoice.invoice_number}`)}>التفاصيل الكاملة</button> }]} /></div>
    : <div className="space-y-4"><h2 className="text-xl font-black">سجل النشاط</h2><DataTable rows={data.audit?.entries || []} empty="لا توجد عمليات ضمن نطاقك." columns={[{ key: 'created_at', label: 'الوقت', render: (entry) => formatDate(entry.created_at, true) }, { key: 'user', label: 'المستخدم', render: (entry) => entry.user?.full_name || 'النظام' }, { key: 'action', label: 'العملية' }, { key: 'company', label: 'الشركة', render: (entry) => entry.company?.company_name || '—' }]} /></div>;

  return <DashboardShell title={title} eyebrow={eyebrow} items={items} active={active} onSelect={setActive}>{loading ? <div className="rounded-2xl bg-white p-10 text-center text-secondary-600 shadow-card">جارٍ تحميل بيانات النطاق…</div> : content}<DetailPanel open={detail.open} title={detail.title} data={detail.data} loading={detail.loading} onClose={() => setDetail({ open: false, title: '', data: null, loading: false })} /><AssignDriverDialog open={Boolean(assigning)} drivers={data.drivers?.drivers?.filter((driver) => driver.is_available && driver.is_active) || []} onSubmit={assignDriver} onClose={() => setAssigning(null)} /><RejectDialog open={Boolean(rejecting)} title={rejecting?.title} onSubmit={async (reason) => { if (rejecting?.product) { const response = await request(() => api.patch(`/platform/products/${rejecting.product.id}/status`, { status: rejecting.status, reason })); if (response) { toast.success('تم رفض المنتج'); setRejecting(null); load(); } } else { setOrderStatus(rejecting.order, rejecting.status, reason); } }} onClose={() => setRejecting(null)} /></DashboardShell>;
}
