'use client';

import { Suspense, useEffect, useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { FiChevronLeft, FiChevronRight, FiFilter, FiX } from 'react-icons/fi';
import api from '@/lib/api';
import ProductCard from '@/components/ProductCard';

const filterKeys = ['search', 'category', 'subCategory', 'condition', 'province', 'university', 'minPrice', 'maxPrice', 'currency', 'sortBy', 'page'];

function ProductsContent() {
  const router = useRouter(); const searchParams = useSearchParams(); const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [pagination, setPagination] = useState({ page: 1, pages: 0, total: 0 }); const [loading, setLoading] = useState(true); const [showFilters, setShowFilters] = useState(false);
  const filters = useMemo(() => Object.fromEntries(filterKeys.map((key) => [key, searchParams.get(key) || (key === 'sortBy' ? 'newest' : '')])), [searchParams]);
  useEffect(() => { api.get('/catalog/categories').then((response) => setCategories(response.categories || [])).catch(() => setCategories([])); }, []);
  useEffect(() => { setLoading(true); const query = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) query.set(key, value); }); query.set('limit', '24'); api.get(`/products?${query}`).then((response) => { setProducts(response.products || []); setPagination(response.pagination || { page: 1, pages: 0, total: 0 }); }).catch(() => { setProducts([]); setPagination({ page: 1, pages: 0, total: 0 }); }).finally(() => setLoading(false)); }, [filters]);
  const setFilter = (key, value) => { const query = new URLSearchParams(searchParams.toString()); if (value) query.set(key, value); else query.delete(key); if (key !== 'page') query.delete('page'); router.push(`/products?${query}`); };
  const reset = () => router.push('/products');
  const activeCategory = categories.find((category) => category.name === filters.category);
  const FilterControl = () => <div className="space-y-5"><label className="block text-sm font-bold">البحث<input value={filters.search} onChange={(event) => setFilter('search', event.target.value)} placeholder="اسم المنتج، الكود أو الوصف" className="input-base mt-2" /></label><label className="block text-sm font-bold">التصنيف<select value={filters.category} onChange={(event) => setFilter('category', event.target.value)} className="input-base mt-2"><option value="">كل التصنيفات</option>{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select></label>{activeCategory?.subCategories?.length > 0 && <label className="block text-sm font-bold">التصنيف الفرعي<select value={filters.subCategory} onChange={(event) => setFilter('subCategory', event.target.value)} className="input-base mt-2"><option value="">الكل</option>{activeCategory.subCategories.map((sub) => <option key={sub.id} value={sub.name}>{sub.name}</option>)}</select></label>}<label className="block text-sm font-bold">الحالة<select value={filters.condition} onChange={(event) => setFilter('condition', event.target.value)} className="input-base mt-2"><option value="">جديد ومستعمل</option><option value="new">جديد</option><option value="used">مستعمل</option></select></label><div className="grid grid-cols-2 gap-3"><label className="block text-sm font-bold">من<input value={filters.minPrice} onChange={(event) => setFilter('minPrice', event.target.value)} type="number" min="0" className="input-base mt-2" /></label><label className="block text-sm font-bold">إلى<input value={filters.maxPrice} onChange={(event) => setFilter('maxPrice', event.target.value)} type="number" min="0" className="input-base mt-2" /></label></div><label className="block text-sm font-bold">العملة<select value={filters.currency} onChange={(event) => setFilter('currency', event.target.value)} className="input-base mt-2"><option value="">كل العملات</option><option value="SYP">ليرة سورية</option><option value="USD">دولار أمريكي</option></select></label><label className="block text-sm font-bold">المحافظة<input value={filters.province} onChange={(event) => setFilter('province', event.target.value)} className="input-base mt-2" /></label><label className="block text-sm font-bold">الجامعة<input value={filters.university} onChange={(event) => setFilter('university', event.target.value)} className="input-base mt-2" /></label><button onClick={reset} className="btn-secondary w-full">مسح الفلاتر</button></div>;
  return <div className="min-h-screen bg-secondary-50"><div className="container-main py-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">المنتجات</h1><p className="mt-2 text-secondary-600">بحث مرن، فلاتر قابلة للمشاركة، وأسعار موحّدة للترتيب.</p></div><div className="flex items-center gap-3"><select value={filters.sortBy} onChange={(event) => setFilter('sortBy', event.target.value)} className="input-base w-auto"><option value="newest">الأحدث</option><option value="oldest">الأقدم</option><option value="cheapest">الأرخص أولاً</option><option value="expensive">الأغلى أولاً</option></select><button onClick={() => setShowFilters(true)} className="btn-secondary lg:hidden"><FiFilter className="ml-2" />فلترة</button></div></div><div className="grid gap-7 lg:grid-cols-[280px_1fr]"><aside className="hidden rounded-2xl bg-white p-5 shadow-card lg:block"><h2 className="mb-5 font-black">الفلاتر</h2><FilterControl /></aside><section><p className="mb-5 text-sm text-secondary-600">{loading ? 'جارٍ البحث...' : `${pagination.total} منتجاً`}</p>{loading ? <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 9 }).map((_, index) => <div key={index} className="h-96 animate-pulse rounded-2xl bg-secondary-200" />)}</div> : products.length ? <><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{products.map((product, index) => <ProductCard key={product.id} product={product} delay={index * 0.02} />)}</div>{pagination.pages > 1 && <div className="mt-8 flex items-center justify-center gap-3"><button disabled={pagination.page <= 1} onClick={() => setFilter('page', String(pagination.page - 1))} className="btn-secondary disabled:opacity-40"><FiChevronRight /></button><span className="text-sm font-bold">صفحة {pagination.page} من {pagination.pages}</span><button disabled={pagination.page >= pagination.pages} onClick={() => setFilter('page', String(pagination.page + 1))} className="btn-secondary disabled:opacity-40"><FiChevronLeft /></button></div>}</> : <div className="rounded-2xl bg-white p-12 text-center shadow-card"><h2 className="text-xl font-black">لا توجد منتجات مطابقة</h2><p className="mt-3 text-secondary-600">غيّر كلمات البحث أو وسّع نطاق الفلاتر.</p><button onClick={reset} className="btn-primary mt-6">عرض كل المنتجات</button></div>}</section></div></div>{showFilters && <div className="fixed inset-0 z-[60] bg-secondary-950/45 p-4 lg:hidden"><aside className="mr-auto h-full max-w-sm overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="font-black">الفلاتر</h2><button onClick={() => setShowFilters(false)} className="rounded-lg p-2 hover:bg-secondary-100"><FiX /></button></div><FilterControl /></aside></div>}</div>;
}

export default function ProductsPage() {
  return <Suspense fallback={<div className="container-main py-20 text-center">جارٍ تحميل الكتالوج...</div>}><ProductsContent /></Suspense>;
}
