'use client';

import Link from 'next/link';
import { FiMinus, FiPlus, FiTrash2 } from 'react-icons/fi';
import RequireAuth from '@/components/RequireAuth';
import ProductImage from '@/components/ProductImage';
import { useCart } from '@/context/CartContext';
import { formatMoney } from '@/lib/format';

function CartContent() {
  const { items, isLoading, busyItemId, updateQuantity, removeItem, clearCart } = useCart();
  const subtotal = items.reduce((sum, item) => sum + (item.available ? Number(item.product?.price_syp || 0) * Number(item.quantity) : 0), 0);
  if (isLoading) return <div className="container-main py-20 text-center">جارٍ تحميل السلة...</div>;
  if (!items.length) return <div className="container-main py-20 text-center"><h1 className="text-3xl font-black">سلتك فارغة</h1><p className="mt-3 text-secondary-600">أضف المنتجات التي تحتاجها ثم أكمل الطلب.</p><Link href="/products" className="btn-primary mt-6">تصفح المنتجات</Link></div>;
  return <div className="min-h-screen bg-secondary-50 py-8"><div className="container-main"><div className="mb-7 flex items-center justify-between"><div><h1 className="text-3xl font-black">سلة التسوق</h1><p className="mt-2 text-secondary-600">تحقق من الكميات قبل الانتقال إلى الفاتورة.</p></div><button onClick={clearCart} className="btn-secondary text-red-700"><FiTrash2 className="ml-2" />إفراغ السلة</button></div><div className="grid gap-7 lg:grid-cols-[1fr_340px]"><section className="space-y-4">{items.map((item) => <article key={item.id} className={`flex gap-4 rounded-2xl bg-white p-4 shadow-card ${!item.available ? 'border border-red-200' : ''}`}><ProductImage src={item.product?.images?.find((image) => image.is_primary)?.image_url || item.product?.images?.[0]?.image_url} alt={item.product?.name} className="h-24 w-24 rounded-xl object-cover" /><div className="min-w-0 flex-1"><Link href={`/products/${item.product?.id}`} className="font-black hover:text-primary-700">{item.product?.name || 'منتج غير متاح'}</Link><p className="mt-1 text-sm text-secondary-500">{item.product?.code}</p><p className="mt-2 font-black text-primary-700">{formatMoney(item.product?.price, item.product?.currency)}</p>{!item.available && <p className="mt-2 text-sm font-bold text-red-700">هذا المنتج لم يعد متاحاً بهذه الكمية. عدّل السلة قبل المتابعة.</p>}<div className="mt-3 flex items-center justify-between"><div className="flex items-center rounded-lg border"><button disabled={item.quantity <= 1 || busyItemId === item.id} onClick={() => updateQuantity(item.id, item.quantity - 1)} className="p-2"><FiMinus /></button><span className="min-w-9 text-center font-bold">{item.quantity}</span><button disabled={item.quantity >= Number(item.product?.stock_quantity) || busyItemId === item.id} onClick={() => updateQuantity(item.id, item.quantity + 1)} className="p-2"><FiPlus /></button></div><button disabled={busyItemId === item.id} onClick={() => removeItem(item.id)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><FiTrash2 /></button></div></div></article>)}</section><aside className="h-fit rounded-2xl bg-white p-6 shadow-card"><h2 className="text-xl font-black">ملخص السلة</h2><div className="mt-5 flex justify-between text-secondary-600"><span>المجموع الفرعي</span><b>{formatMoney(subtotal, 'SYP')}</b></div><p className="mt-4 rounded-xl bg-secondary-50 p-3 text-xs leading-6 text-secondary-600">يُحسب الخصم والتوصيل بدقة حسب الشركة والمحافظة والسرعة في صفحة إتمام الطلب.</p><Link href="/checkout" className={`btn-primary mt-6 w-full ${items.some((item) => !item.available) ? 'pointer-events-none opacity-50' : ''}`}>متابعة لإتمام الطلب</Link></aside></div></div></div>;
}
export default function CartPage() { return <RequireAuth role="customer"><CartContent /></RequireAuth>; }
