import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import api, { errorText } from './api';

const C = { primary: '#0f766e', dark: '#115e59', ink: '#172033', muted: '#64748b', bg: '#f1f5f9', card: '#fff', border: '#dbe4ea', danger: '#b91c1c', success: '#047857' };
const money = (value, currency = 'SYP') => `${Number(value || 0).toLocaleString('ar-SY')} ${currency === 'USD' ? '$' : 'ل.س'}`;
const label = (value) => ({ new: 'جديد', pending_review: 'قيد المراجعة', approved: 'معتمد', preparing: 'قيد التجهيز', ready_for_delivery: 'جاهز للتوصيل', assigned_to_driver: 'مع السائق', in_delivery: 'قيد التوصيل', delivered: 'تم التسليم', completed: 'مكتمل', rejected: 'مرفوض', inactive: 'غير فعال' }[value] || value || '—');
function Btn({ title, onPress, secondary = false, danger = false }) { return <Pressable onPress={onPress} style={[s.btn, secondary && s.btnSecondary, danger && s.btnDanger]}><Text style={[s.btnText, secondary && s.btnSecondaryText, danger && s.btnDangerText]}>{title}</Text></Pressable>; }
function Card({ children, onPress }) { return <Pressable onPress={onPress} style={s.card}>{children}</Pressable>; }
function Header({ title, subtitle }) { return <><Text style={s.brand}>TopDent</Text><Text style={s.title}>{title}</Text><Text style={s.subtitle}>{subtitle}</Text></>; }
function Search({ value, onChangeText }) { return <TextInput value={value} onChangeText={onChangeText} placeholder="بحث وتصفية..." placeholderTextColor="#94a3b8" style={s.search} />; }
function Tabs({ tabs, active, onChange }) { return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{tabs.map((tab) => <Pressable key={tab.id} onPress={() => onChange(tab.id)} style={[s.tab, active === tab.id && s.tabActive]}><Text style={[s.tabText, active === tab.id && s.tabTextActive]}>{tab.label}</Text></Pressable>)}</ScrollView>; }

const baseTabs = [{ id: 'overview', label: 'الرئيسية' }, { id: 'orders', label: 'الطلبات' }, { id: 'products', label: 'المنتجات' }];
const adminTabs = [...baseTabs, { id: 'companies', label: 'الشركات' }, { id: 'drivers', label: 'السائقون' }, { id: 'invoices', label: 'الفواتير' }, { id: 'roles', label: 'الأدوار' }, { id: 'catalog', label: 'الكتالوج' }, { id: 'audit', label: 'سجل النشاط' }, { id: 'settings', label: 'الإعدادات' }];
const merchantTabs = [...baseTabs, { id: 'sales', label: 'المبيعات' }, { id: 'delivery', label: 'التوصيل' }, { id: 'profile', label: 'بيانات الشركة' }];

export function OperationsScreen({ user, navigation, route }) {
  const roles = user?.roles || []; const isMerchant = user?.role === 'merchant' || roles.includes('company_manager') || roles.includes('company_admin'); const isDriver = user?.role === 'driver' || roles.includes('platform_driver') || roles.includes('company_driver'); const tabs = isMerchant ? merchantTabs : isDriver ? [{ id: 'overview', label: 'الرئيسية' }, { id: 'orders', label: 'مهام التوصيل' }] : adminTabs;
  const [active, setActive] = useState(route?.params?.section || 'overview'); const [data, setData] = useState({}); const [loading, setLoading] = useState(false); const [query, setQuery] = useState(''); const [error, setError] = useState('');
  const urls = useMemo(() => ({ overview: isMerchant ? '/merchants/dashboard' : isDriver ? '/orders/driver/assignments' : '/platform/dashboard', orders: isMerchant ? '/merchants/orders' : isDriver ? '/orders/driver/assignments' : '/platform/orders?limit=50', products: isMerchant ? '/merchants/products' : '/platform/products?limit=50', sales: '/merchants/sales', delivery: '/delivery-rates/merchant', profile: '/merchants/dashboard', companies: '/platform/companies?limit=50', drivers: '/platform/drivers?limit=50', invoices: '/platform/invoices?limit=50', roles: '/platform/roles', catalog: '/platform/catalog/categories', audit: '/platform/audit-log?limit=50', settings: '/platform/settings' }), [isMerchant, isDriver]);
  const load = async (section = active) => { setLoading(true); setError(''); try { const r = await api.get(urls[section]); setData((current) => ({ ...current, [section]: r })); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } };
  useFocusEffect(React.useCallback(() => { load(active); }, [active, urls]));
  const request = async (method, path, body) => { try { await api[method](path, body); Alert.alert('تم الحفظ', 'تم تحديث البيانات بنجاح'); load(active); } catch (e) { Alert.alert('تعذر التنفيذ', errorText(e)); } };
  const source = data[active] || {}; const list = source.orders || source.products || source.companies || source.drivers || source.invoices || source.roles || source.categories || source.logs || source.audit || source.assignments || [];
  const visible = Array.isArray(list) ? list.filter((x) => JSON.stringify(x).toLowerCase().includes(query.toLowerCase())) : [];
  const renderRow = (item, index) => { const name = item.order_number || item.name || item.company_name || item.invoice_number || item.user?.full_name || item.role_name || item.action || `سجل ${index + 1}`; const detail = item.status ? label(item.status) : item.total ? money(item.total, item.currency) : item.email || item.description || item.created_at || ''; return <Card key={item.id || index}><View style={s.row}><View style={s.flex}><Text style={s.rowTitle}>{name}</Text><Text style={s.muted}>{detail}</Text>{item.customer?.full_name && <Text style={s.muted}>العميل: {item.customer.full_name}</Text>}{item.merchant?.company_name && <Text style={s.muted}>الشركة: {item.merchant.company_name}</Text>}</View><Text style={s.status}>{item.status ? label(item.status) : ''}</Text></View><View style={s.actions}>{active === 'orders' && !isDriver && item.status === 'new' && <Btn title="بدء المراجعة" onPress={() => request('patch', `/platform/orders/${item.id}/status`, { status: 'pending_review' })} />}{active === 'orders' && !isDriver && item.status === 'pending_review' && <><Btn title="موافقة" onPress={() => request('patch', `/platform/orders/${item.id}/status`, { status: 'approved' })} /><Btn title="رفض" danger secondary onPress={() => request('patch', `/platform/orders/${item.id}/status`, { status: 'rejected', reason: 'رفض من لوحة التشغيل' })} /></>}{active === 'orders' && isDriver && item.status === 'assigned_to_driver' && <Btn title="بدء التوصيل" onPress={() => request('post', `/orders/${item.id}/driver/accept`, {})} />}{active === 'orders' && isDriver && item.status === 'in_delivery' && <Btn title="تم الوصول" onPress={() => request('post', `/orders/${item.id}/driver/arrive`, {})} />}{active === 'orders' && isDriver && item.status === 'arrived' && <Btn title="تم التسليم" onPress={() => request('post', `/orders/${item.id}/driver/deliver`, {})} />}{active === 'products' && item.status === 'pending' && <Btn title="اعتماد المنتج" onPress={() => request('patch', `/platform/products/${item.id}/status`, { status: 'approved' })} />}{active === 'products' && item.is_active && <Btn title="إخفاء" danger secondary onPress={() => request('patch', `/platform/products/${item.id}/status`, { status: 'inactive' })} />}{active === 'companies' && <Btn title={item.is_active ? 'تعطيل' : 'تفعيل'} secondary onPress={() => request('patch', `/platform/companies/${item.id}/status`, { isActive: !item.is_active })} />}{active === 'drivers' && <Btn title={item.is_active ? 'تعطيل' : 'تفعيل'} secondary onPress={() => request('patch', `/platform/drivers/${item.id}/status`, { isActive: !item.is_active, isAvailable: item.is_available })} />}{active === 'invoices' && <Btn title="تفاصيل الفاتورة" secondary onPress={() => navigation.navigate('InvoiceDetail', { id: item.id })} />}</View></Card>; };
  return <ScrollView style={s.screen} contentContainerStyle={s.content}><Header title="مساحة التشغيل" subtitle={isMerchant ? 'إدارة شركتك ومنتجاتك ومبيعاتك' : isDriver ? 'مهام التوصيل وتحديث حالتها' : 'إدارة كاملة للمنصة حسب الصلاحيات'} /><Tabs tabs={tabs} active={active} onChange={setActive} />{active !== 'overview' && <Search value={query} onChangeText={setQuery} />}{loading ? <Text style={s.muted}>جارٍ تحميل البيانات...</Text> : error ? <Text style={s.error}>{error}</Text> : active === 'overview' ? <Overview data={source} isMerchant={isMerchant} isDriver={isDriver} navigation={navigation} /> : active === 'profile' ? <MerchantProfile data={source} request={request} /> : active === 'delivery' ? <MerchantDelivery data={source} request={request} /> : active === 'roles' ? <RoleSummary data={source} /> : active === 'catalog' ? <CatalogSummary data={source} /> : visible.length ? visible.map(renderRow) : <Text style={s.empty}>لا توجد بيانات ضمن هذا القسم.</Text>}</ScrollView>;
}

function Overview({ data, isMerchant, isDriver, navigation }) { const stats = data.stats || data; return <><View style={s.stats}>{[['الطلبات', stats.orders || data.orders?.length || data.assignments?.length || 0], ['المنتجات', stats.products || data.products?.length || 0], ['المبيعات', stats.totalSales ? money(stats.totalSales) : '—']].map(([title, value]) => <Card key={title}><Text style={s.stat}>{value}</Text><Text style={s.muted}>{title}</Text></Card>)}</View><Text style={s.section}>إجراءات سريعة</Text><View style={s.actions}><Btn title="فتح الطلبات" onPress={() => navigation.navigate('Operations', { section: 'orders' })} /><Btn title="المنتجات" secondary onPress={() => navigation.navigate('Operations', { section: 'products' })} />{isMerchant && <Btn title="إضافة منتج" onPress={() => navigation.navigate('Sell')} />}{isDriver && <Btn title="تحديث المهام" secondary onPress={() => navigation.navigate('Operations', { section: 'orders' })} />}</View><Text style={s.body}>كل إجراء هنا يمر عبر نفس حماية الصلاحيات الموجودة في الموقع، ولا يمكن للتطبيق تجاوز صلاحيات الحساب.</Text></>; }
function MerchantProfile({ data }) { return <Card><Text style={s.rowTitle}>{data.company_name || data.company?.company_name || 'بيانات الشركة'}</Text><Text style={s.body}>{data.company_description || data.company?.description || 'يمكن تعديل الملف من قسم إعدادات الشركة.'}</Text></Card>; }
function MerchantDelivery({ data }) { const rates = data.rates || data.deliveryRates || []; return rates.length ? rates.map((x, i) => <Card key={x.speed || i}><Text style={s.rowTitle}>{x.speed || x.delivery_speed}</Text><Text style={s.muted}>التكلفة: {money(x.cost || x.price)}</Text></Card>) : <Text style={s.empty}>لا توجد تعرفة توصيل معروضة.</Text>; }
function RoleSummary({ data }) { return <>{(data.roles || []).map((role) => <Card key={role.id}><Text style={s.rowTitle}>{role.name || role.role_name}</Text><Text style={s.muted}>{role.permissions?.length || 0} صلاحية</Text></Card>)}<Text style={s.body}>تعديل الأدوار يتم وفق صلاحيات roles.assign وroles.update الموجودة في الحساب.</Text></>; }
function CatalogSummary({ data }) { return <>{(data.categories || []).map((category) => <Card key={category.id}><Text style={s.rowTitle}>{category.name}</Text><Text style={s.muted}>{category.subCategories?.length || 0} تصنيف فرعي</Text></Card>)}<Text style={s.body}>إدارة التصنيفات والجامعات متاحة للحسابات التي تملك catalog.manage.</Text></>; }

export function InvoiceDetail({ route }) { const [data, setData] = useState(null); useEffect(() => { api.get(`/platform/invoices/${route.params.id}`).then(setData).catch(() => {}); }, [route.params.id]); return <ScrollView style={s.screen} contentContainerStyle={s.content}><Header title="تفاصيل الفاتورة" subtitle="بيانات الفاتورة والتحصيل" />{data ? <Card><Text style={s.rowTitle}>{data.invoice_number || data.invoice?.invoice_number}</Text><Text style={s.body}>{JSON.stringify(data.invoice || data, null, 2)}</Text></Card> : <Text style={s.muted}>جارٍ تحميل الفاتورة...</Text>}</ScrollView>; }

const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: C.bg }, content: { padding: 18, paddingBottom: 45 }, brand: { color: C.primary, fontSize: 18, fontWeight: '900', textAlign: 'right', marginBottom: 8 }, title: { color: C.ink, fontSize: 28, fontWeight: '900', textAlign: 'right' }, subtitle: { color: C.muted, textAlign: 'right', marginTop: 5, marginBottom: 18 }, tabs: { flexDirection: 'row-reverse', gap: 8, paddingBottom: 12 }, tab: { borderRadius: 20, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: '#fff', borderWidth: 1, borderColor: C.border }, tabActive: { backgroundColor: '#ccfbf1', borderColor: C.primary }, tabText: { color: C.muted, fontWeight: '800' }, tabTextActive: { color: C.primary }, search: { backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, textAlign: 'right', color: C.ink, marginBottom: 12 }, card: { backgroundColor: C.card, borderRadius: 17, padding: 15, marginBottom: 12, elevation: 2 }, row: { flexDirection: 'row-reverse', alignItems: 'flex-start', gap: 10 }, flex: { flex: 1 }, rowTitle: { color: C.ink, fontSize: 16, fontWeight: '900', textAlign: 'right' }, muted: { color: C.muted, textAlign: 'right', fontSize: 13, marginTop: 5 }, status: { color: C.primary, fontSize: 12, fontWeight: '900' }, body: { color: '#475569', textAlign: 'right', lineHeight: 24, marginTop: 10 }, btn: { backgroundColor: C.primary, borderRadius: 11, paddingHorizontal: 13, paddingVertical: 10, marginTop: 10 }, btnSecondary: { backgroundColor: '#fff', borderWidth: 1, borderColor: C.primary }, btnDanger: { backgroundColor: '#fff', borderColor: '#fecaca', borderWidth: 1 }, btnText: { color: '#fff', fontWeight: '900', textAlign: 'center' }, btnSecondaryText: { color: C.primary }, btnDangerText: { color: C.danger }, actions: { flexDirection: 'row-reverse', flexWrap: 'wrap', gap: 8 }, stats: { flexDirection: 'row-reverse', gap: 10 }, stat: { color: C.primary, fontSize: 26, fontWeight: '900', textAlign: 'right' }, section: { color: C.ink, fontSize: 20, fontWeight: '900', textAlign: 'right', marginTop: 18, marginBottom: 8 }, empty: { color: C.muted, textAlign: 'center', paddingVertical: 35 }, error: { color: C.danger, textAlign: 'right', paddingVertical: 25 } });
