'use client';

import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import RequireAuth from '@/components/RequireAuth';
import api from '@/lib/api';
import { apiError } from '@/lib/format';
import { useAuth } from '@/context/AuthContext';

function ProfileContent() { const { logout } = useAuth(); const [form, setForm] = useState(null); const [password, setPassword] = useState({ currentPassword: '', password: '', passwordConfirmation: '' });
  useEffect(() => { api.get('/users/me').then((user) => setForm({ fullName: user.full_name || '', phone: user.phone || '', whatsapp: user.whatsapp || '', province: user.province || '', area: user.area || '', address: user.address || '', universityClinic: user.university_clinic || '', avatarUrl: user.avatar_url || '' })).catch((err) => toast.error(apiError(err))); }, []);
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value })); const save = async (event) => { event.preventDefault(); try { await api.put('/users/me', form); toast.success('تم تحديث الملف الشخصي'); } catch (err) { toast.error(apiError(err)); } }; const changePassword = async (event) => { event.preventDefault(); try { const response = await api.post('/auth/change-password', password); toast.success(response.message); setPassword({ currentPassword: '', password: '', passwordConfirmation: '' }); } catch (err) { toast.error(apiError(err)); } }; const disable = async () => { if (!window.confirm('سيتم تعطيل الحساب وتسجيل خروجك. هل تريد المتابعة؟')) return; try { await api.post('/auth/disable-account'); logout(); toast.success('تم تعطيل الحساب'); window.location.assign('/'); } catch (err) { toast.error(apiError(err)); } };
  if (!form) return <div className="container-main py-20 text-center">جارٍ تحميل الملف...</div>; return <div className="min-h-screen bg-secondary-50 py-8"><div className="container-main grid max-w-5xl gap-7 lg:grid-cols-2"><form onSubmit={save} className="rounded-2xl bg-white p-6 shadow-card"><h1 className="text-2xl font-black">الملف الشخصي</h1><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['fullName', 'الاسم الثلاثي'], ['phone', 'الهاتف'], ['whatsapp', 'واتساب'], ['province', 'المحافظة'], ['area', 'المنطقة'], ['address', 'العنوان'], ['universityClinic', 'الجامعة / العيادة'], ['avatarUrl', 'رابط الصورة الشخصية']].map(([name, label]) => <label key={name} className="text-sm font-bold">{label}<input required={['fullName', 'phone', 'province', 'area'].includes(name)} name={name} value={form[name]} onChange={update} className="input-base mt-2" /></label>)}</div><button className="btn-primary mt-6">حفظ التعديلات</button></form><div className="space-y-7"><form onSubmit={changePassword} className="rounded-2xl bg-white p-6 shadow-card"><h2 className="text-xl font-black">تغيير كلمة المرور</h2><div className="mt-5 space-y-3">{[['currentPassword', 'كلمة المرور الحالية'], ['password', 'كلمة المرور الجديدة'], ['passwordConfirmation', 'تأكيد كلمة المرور الجديدة']].map(([name, label]) => <label key={name} className="block text-sm font-bold">{label}<input required minLength="8" type="password" value={password[name]} onChange={(event) => setPassword((current) => ({ ...current, [name]: event.target.value }))} className="input-base mt-2" /></label>)}</div><button className="btn-primary mt-5">تغيير كلمة المرور</button></form><section className="rounded-2xl border border-red-200 bg-red-50 p-6"><h2 className="text-xl font-black text-red-900">تعطيل الحساب</h2><p className="mt-2 text-sm leading-6 text-red-800">يمكنك تعطيل الحساب من هنا. لن تحذف البيانات التجارية أو سجل الطلبات، ويستلزم إعادة التفعيل التواصل مع الإدارة.</p><button onClick={disable} className="mt-5 rounded-lg bg-red-600 px-4 py-2.5 font-bold text-white">تعطيل الحساب</button></section></div></div></div>; }
export default function ProfilePage() { return <RequireAuth><ProfileContent /></RequireAuth>; }
